---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: airflow
spec:
  volumes:
    - name: airflow-dag
      persistentVolumeClaim:
        claimName: airflow-dag
  containers:
    - name: task-pv-container
      image: busybox
      command: ["/bin/sh", "-ec", "sleep 1000"]
      volumeMounts:
        - mountPath: "/opt/airflow/mounted-from-host/dags"
          name: airflow-dag
        - mountPath: "/opt/airflow/mounted-from-host/airflow-local"
          name: airflow-local
