kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /opt/airflow/mounted-from-host/
  storageClassName: airflow-storageclass
  claimRef:
    name: airflow-home
    namespace: airflow
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-home
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: airflow-storageclass
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: airflow-log
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 2Gi
#   hostPath:
#     path: /opt/airflow/logs/
#   storageClassName: airflow-storageclass
#   claimRef:
#     name: airflow-log
#     namespace: airflow
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: airflow-log
#   namespace: airflow
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: airflow-storageclass
